# ---------- development image ----------
FROM python:3.11-slim

# системные зависимости
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# рабочая директория
WORKDIR /app

# установка зависимостей
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# копируем проект (но в dev будет перекрыто volume)
COPY . .

# uvicorn в dev-режиме
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
