"""add owner_id to items

Revision ID: 26565b90f9ac
Revises: d3f25251a473
Create Date: 2025-11-12 16:10:28.278628

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26565b90f9ac"
down_revision: Union[str, Sequence[str], None] = "d3f25251a473"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("owner_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_items_owner_id"), "items", ["owner_id"], unique=False)
    op.create_foreign_key(
        "fk_items_owner_id", "items", "users", ["owner_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_items_owner_id", "items", type_="foreignkey")
    op.drop_index(op.f("ix_items_owner_id"), table_name="items")
    op.drop_column("items", "owner_id")
    # ### end Alembic commands ###
