"""fix foreign key names and types

Revision ID: 7a71783057b8
Revises: 1c031eb0e917
Create Date: 2025-11-04 15:33:32.467738

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a71783057b8"
down_revision: Union[str, Sequence[str], None] = "1c031eb0e917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("items", "category_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_index(
        op.f("ix_items_category_id"), "items", ["category_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_items_category_id"), table_name="items")
    op.alter_column("items", "category_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
