"""add categories table and relation to items

Revision ID: 82c8c659483e
Revises: e66602829d61
Create Date: 2025-10-14 10:15:31.893977

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "82c8c659483e"
down_revision: Union[str, Sequence[str], None] = "e66602829d61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)
    op.add_column("items", sa.Column("category_id", sa.Integer(), nullable=False))
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "items",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=False)
    op.create_foreign_key(None, "items", "categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="foreignkey")
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.alter_column(
        "items",
        "price",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column("items", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("items", "category_id")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
