"""ensure_owner_id

Revision ID: d5d9b26441db
Revises: 929deca17e84
Create Date: 2025-12-15 17:54:44.728193

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5d9b26441db"
down_revision: Union[str, Sequence[str], None] = "929deca17e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [c["name"] for c in inspector.get_columns("items")]

    if "owner_id" not in columns:
        op.add_column("items", sa.Column("owner_id", sa.Integer(), nullable=True))
        op.create_index(op.f("ix_items_owner_id"), "items", ["owner_id"], unique=False)
        op.create_foreign_key(
            "fk_items_owner_id", "items", "users", ["owner_id"], ["id"]
        )
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
