"""add indexes for items pagination and filters

Revision ID: dc937df16a7c
Revises: 82c8c659483e
Create Date: 2025-10-15 13:36:38.478248

"""

from typing import Sequence, Union

# import sqlalchemy as sa
# from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc937df16a7c"
down_revision: Union[str, Sequence[str], None] = "82c8c659483e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
